// Arithmetic
#pragma kernel Add
#pragma kernel Subtract
#pragma kernel Multiply
#pragma kernel Divide
#pragma kernel Average

// Darken
#pragma kernel Darken
#pragma kernel ColorBurn
#pragma kernel LinearBurn
#pragma kernel GammaDark

// Lighten
#pragma kernel Lighten
#pragma kernel Shine
#pragma kernel Screen
#pragma kernel ColorDodge
#pragma kernel Overlay
#pragma kernel SoftLight
#pragma kernel HardLight
#pragma kernel LinearLight
#pragma kernel HardMix
#pragma kernel Tint
#pragma kernel GammaLight
#pragma kernel GammaIllumination

// Other
#pragma kernel Exclusion
#pragma kernel Difference
#pragma kernel Negation

#include "Formulas.hlsl"

RWStructuredBuffer<float4> result;

StructuredBuffer<float4> base;
StructuredBuffer<float4> blend;

// Arithmetic
[numthreads(1024, 1, 1)]
void Add(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Add(base[id.x].x, blend[id.x].x);
    result[id.x].y = Add(base[id.x].y, blend[id.x].y);
    result[id.x].z = Add(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void Subtract(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Subtract(base[id.x].x, blend[id.x].x);
    result[id.x].y = Subtract(base[id.x].y, blend[id.x].y);
    result[id.x].z = Subtract(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void Multiply(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Multiply(base[id.x].x, blend[id.x].x);
    result[id.x].y = Multiply(base[id.x].y, blend[id.x].y);
    result[id.x].z = Multiply(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void Divide(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Divide(base[id.x].x, blend[id.x].x);
    result[id.x].y = Divide(base[id.x].y, blend[id.x].y);
    result[id.x].z = Divide(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void Average(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Average(base[id.x].x, blend[id.x].x);
    result[id.x].y = Average(base[id.x].y, blend[id.x].y);
    result[id.x].z = Average(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

// Darken
[numthreads(1024, 1, 1)]
void Darken(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Darken(base[id.x].x, blend[id.x].x);
    result[id.x].y = Darken(base[id.x].y, blend[id.x].y);
    result[id.x].z = Darken(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void ColorBurn(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = ColorBurn(base[id.x].x, blend[id.x].x);
    result[id.x].y = ColorBurn(base[id.x].y, blend[id.x].y);
    result[id.x].z = ColorBurn(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void LinearBurn(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = LinearBurn(base[id.x].x, blend[id.x].x);
    result[id.x].y = LinearBurn(base[id.x].y, blend[id.x].y);
    result[id.x].z = LinearBurn(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void GammaDark(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = GammaDark(base[id.x].x, blend[id.x].x);
    result[id.x].y = GammaDark(base[id.x].y, blend[id.x].y);
    result[id.x].z = GammaDark(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

// Lighten
[numthreads(1024, 1, 1)]
void Lighten(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Lighten(base[id.x].x, blend[id.x].x);
    result[id.x].y = Lighten(base[id.x].y, blend[id.x].y);
    result[id.x].z = Lighten(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void Shine(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Shine(base[id.x].x, blend[id.x].x);
    result[id.x].y = Shine(base[id.x].y, blend[id.x].y);
    result[id.x].z = Shine(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void Screen(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Screen(base[id.x].x, blend[id.x].x);
    result[id.x].y = Screen(base[id.x].y, blend[id.x].y);
    result[id.x].z = Screen(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void ColorDodge(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = ColorDodge(base[id.x].x, blend[id.x].x);
    result[id.x].y = ColorDodge(base[id.x].y, blend[id.x].y);
    result[id.x].z = ColorDodge(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void Overlay(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Overlay(base[id.x].x, blend[id.x].x);
    result[id.x].y = Overlay(base[id.x].y, blend[id.x].y);
    result[id.x].z = Overlay(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void SoftLight(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = SoftLight(base[id.x].x, blend[id.x].x);
    result[id.x].y = SoftLight(base[id.x].y, blend[id.x].y);
    result[id.x].z = SoftLight(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void HardLight(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = HardLight(base[id.x].x, blend[id.x].x);
    result[id.x].y = HardLight(base[id.x].y, blend[id.x].y);
    result[id.x].z = HardLight(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void LinearLight(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = LinearLight(base[id.x].x, blend[id.x].x);
    result[id.x].y = LinearLight(base[id.x].y, blend[id.x].y);
    result[id.x].z = LinearLight(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void HardMix(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = HardMix(base[id.x].x, blend[id.x].x);
    result[id.x].y = HardMix(base[id.x].y, blend[id.x].y);
    result[id.x].z = HardMix(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void Tint(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Tint(base[id.x].x, blend[id.x].x);
    result[id.x].y = Tint(base[id.x].y, blend[id.x].y);
    result[id.x].z = Tint(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void GammaLight(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = GammaLight(base[id.x].x, blend[id.x].x);
    result[id.x].y = GammaLight(base[id.x].y, blend[id.x].y);
    result[id.x].z = GammaLight(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void GammaIllumination(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = GammaIllumination(base[id.x].x, blend[id.x].x);
    result[id.x].y = GammaIllumination(base[id.x].y, blend[id.x].y);
    result[id.x].z = GammaIllumination(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

// Other
[numthreads(1024, 1, 1)]
void Exclusion(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Exclusion(base[id.x].x, blend[id.x].x);
    result[id.x].y = Exclusion(base[id.x].y, blend[id.x].y);
    result[id.x].z = Exclusion(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void Difference(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Difference(base[id.x].x, blend[id.x].x);
    result[id.x].y = Difference(base[id.x].y, blend[id.x].y);
    result[id.x].z = Difference(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}

[numthreads(1024, 1, 1)]
void Negation(uint3 id : SV_DispatchThreadID)
{
    result[id.x].x = Negation(base[id.x].x, blend[id.x].x);
    result[id.x].y = Negation(base[id.x].y, blend[id.x].y);
    result[id.x].z = Negation(base[id.x].z, blend[id.x].z);
    result[id.x].w = 1.0f;
}