#pragma kernel Noise2D
#pragma kernel Noise3D
#pragma kernel WarpNoise2D
#pragma kernel WarpNoise3D
#pragma kernel Noise2D_Linear
#pragma kernel Noise3D_Linear
#pragma kernel WarpNoise2D_Linear
#pragma kernel WarpNoise3D_Linear

#include "./NoiseGenerator.hlsl"

int width, height;
float halfWidth, halfHeight;

float2 canvasToScreenRatio;

float2 scale;
float3 offset;

float2 warpScale;
float3 warpOffset;

RWStructuredBuffer<float> noise;

fnl_state noiseState;

// Noise
int seed;
float frequency;
int noiseType;

// Fractal
int fractalType;
int octaves;
float lacunarity;
float gain;
float weightedStrength;
float pingPong;

// Cellular
int cellularDistanceFunction;
int cellularReturnType;
float jitter;

void NoiseInit()
{
    fnlCreateState(seed);
    
    noiseState.seed = seed;
    noiseState.frequency = frequency;
    noiseState.noise_type = noiseType;
    noiseState.rotation_type_3d = 0;
    noiseState.fractal_type = fractalType;
    noiseState.octaves = octaves;
    noiseState.lacunarity = lacunarity;
    noiseState.gain = gain;
    noiseState.weighted_strength = weightedStrength;
    noiseState.ping_pong_strength = pingPong;
    noiseState.cellular_distance_func = cellularDistanceFunction;
    noiseState.cellular_return_type = cellularReturnType;
    noiseState.cellular_jitter_mod = jitter;
}

fnl_state warpState;

// Warp
float warpAmp;

// Warp Noise
int warpSeed;
float warpFrequency;
int warpNoiseType;

// Warp Fractal
int warpFractalType;
int warpOctaves;
float warpLacunarity;
float warpGain;
float warpWeightedStrength;
float warpPingPong;

// Warp Cellular
int warpCellularDistanceFunction;
int warpCellularReturnType;
float warpJitter;

void WarpInit()
{
    fnlCreateState(seed);
    
    warpState.seed = warpSeed;
    warpState.frequency = warpFrequency;
    warpState.noise_type = warpNoiseType;
    warpState.rotation_type_3d = 0;
    warpState.fractal_type = warpFractalType;
    warpState.octaves = warpOctaves;
    warpState.lacunarity = warpLacunarity;
    warpState.gain = warpGain;
    warpState.weighted_strength = warpWeightedStrength;
    warpState.ping_pong_strength = warpPingPong;
    warpState.cellular_distance_func = warpCellularDistanceFunction;
    warpState.cellular_return_type = warpCellularReturnType;
    warpState.cellular_jitter_mod = warpJitter;
}

int Index(int x, int y)
{
    if (x >= width ||y >= height)
    {
        return -1;
    }
    
    return y * width + x;
}

float NoisePosX(float x)
{
    return ((x - halfWidth) / scale.x) + offset.x;
}
float NoisePosY(float y)
{
    return ((y - halfHeight) / scale.y) + offset.y;
}

float WarpPosX(float x)
{
    return ((x / warpScale.x) + warpOffset.x) / canvasToScreenRatio.x;
}
float WarpPosY(float y)
{
    return ((y / warpScale.y) + warpOffset.y) / canvasToScreenRatio.y;
}

// Non-Linear

[numthreads(32, 32, 1)]
void Noise2D(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    noise[index] = Single(noiseState, NoisePosX(id.x), NoisePosY(id.y));
}

[numthreads(32, 32, 1)]
void Noise3D(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    noise[index] = Single(noiseState, NoisePosX(id.x), NoisePosY(id.y), offset.z);
}

[numthreads(32, 32, 1)]
void WarpNoise2D(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    NoiseInit();
    WarpInit();
    
    float xNoise = NoisePosX(id.x);
    float yNoise = NoisePosY(id.y);
    
    noise[index] = Single(noiseState, xNoise, yNoise, warpState, WarpPosX(xNoise), WarpPosY(yNoise), warpAmp);
}

[numthreads(32, 32, 1)]
void WarpNoise3D(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    WarpInit();
    
    float xNoise = NoisePosX(id.x);
    float yNoise = NoisePosY(id.y);
            
    noise[index] = Single(noiseState, xNoise, yNoise, offset.z, warpState, WarpPosX(xNoise), WarpPosY(yNoise), warpOffset.z, warpAmp);
}

// Linear

[numthreads(32, 32, 1)]
void Noise2D_Linear(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    noise[index] = Single_Linear(noiseState, NoisePosX(id.x), NoisePosY(id.y));
}

[numthreads(32, 32, 1)]
void Noise3D_Linear(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    noise[index] = Single_Linear(noiseState, NoisePosX(id.x), NoisePosY(id.y), offset.z);
}

[numthreads(32, 32, 1)]
void WarpNoise2D_Linear(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    WarpInit();
    
    float xNoise = NoisePosX(id.x);
    float yNoise = NoisePosY(id.y);
    
    noise[index] = Single_Linear(noiseState, xNoise, yNoise, warpState, WarpPosX(xNoise), WarpPosY(yNoise), warpAmp);
}

[numthreads(32, 32, 1)]
void WarpNoise3D_Linear(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    WarpInit();
    
    float xNoise = NoisePosX(id.x);
    float yNoise = NoisePosY(id.y);
            
    noise[index] = Single_Linear(noiseState, xNoise, yNoise, offset.z, warpState, WarpPosX(xNoise), WarpPosY(yNoise), warpOffset.z, warpAmp);
}