#pragma kernel Noise2D
#pragma kernel Noise2D_Roll
#pragma kernel Noise3D
#pragma kernel Noise3D_Roll
#pragma kernel WarpNoise2D
#pragma kernel WarpNoise2D_Roll
#pragma kernel WarpNoise3D
#pragma kernel WarpNoise3D_Roll
#pragma kernel Noise2D_Linear
#pragma kernel Noise2D_Linear_Roll
#pragma kernel Noise3D_Linear
#pragma kernel Noise3D_Linear_Roll
#pragma kernel WarpNoise2D_Linear
#pragma kernel WarpNoise2D_Linear_Roll
#pragma kernel WarpNoise3D_Linear
#pragma kernel WarpNoise3D_Linear_Roll

#include "../Libraries/FastNoiseLite.hlsl"

float sin, cos;

int width, height;
float halfWidth, halfHeight;

float2 canvasToScreenRatio;

float2 scale;
float3 offset;

float2 warpScale;
float3 warpOffset;

RWStructuredBuffer<float> noise;

fnl_state noiseState;

// Noise
int seed;
float frequency;
int noiseType;

// Fractal
int fractalType;
int octaves;
float lacunarity;
float gain;
float weightedStrength;
float pingPong;

// Cellular
int cellularDistanceFunction;
int cellularReturnType;
float jitter;

void NoiseInit()
{
    fnlCreateState(seed);
    
    noiseState.seed = seed;
    noiseState.frequency = frequency;
    noiseState.noise_type = noiseType;
    noiseState.rotation_type_3d = 0;
    noiseState.fractal_type = fractalType;
    noiseState.octaves = octaves;
    noiseState.lacunarity = lacunarity;
    noiseState.gain = gain;
    noiseState.weighted_strength = weightedStrength;
    noiseState.ping_pong_strength = pingPong;
    noiseState.cellular_distance_func = cellularDistanceFunction;
    noiseState.cellular_return_type = cellularReturnType;
    noiseState.cellular_jitter_mod = jitter;
}

fnl_state warpState;

// Warp
float warpAmp;

// Warp Noise
int warpSeed;
float warpFrequency;
int warpNoiseType;

// Warp Fractal
int warpFractalType;
int warpOctaves;
float warpLacunarity;
float warpGain;
float warpWeightedStrength;
float warpPingPong;

// Warp Cellular
int warpCellularDistanceFunction;
int warpCellularReturnType;
float warpJitter;

void WarpInit()
{
    fnlCreateState(seed);
    
    warpState.seed = warpSeed;
    warpState.frequency = warpFrequency;
    warpState.noise_type = warpNoiseType;
    warpState.rotation_type_3d = 0;
    warpState.fractal_type = warpFractalType;
    warpState.octaves = warpOctaves;
    warpState.lacunarity = warpLacunarity;
    warpState.gain = warpGain;
    warpState.weighted_strength = warpWeightedStrength;
    warpState.ping_pong_strength = warpPingPong;
    warpState.cellular_distance_func = warpCellularDistanceFunction;
    warpState.cellular_return_type = warpCellularReturnType;
    warpState.cellular_jitter_mod = warpJitter;
}


// Noise Generation Function

// Non-Linear

float Single(float2 coord)
{
    return fnlGetNoise2D(noiseState, coord.x - offset.x, coord.y - offset.y);
}

float Single(float3 coord)
{
    return fnlGetNoise3D(noiseState, coord.x - offset.x, coord.y - offset.y, coord.z - offset.z);
}

float Single(float2 coord, float2 warp, float amp)
{
    return Single(
        float2(
            coord.x + fnlGetNoise2D(warpState, warp.x, warp.y) * amp,
            coord.y + fnlGetNoise2D(warpState, warp.y, warp.x) * amp
        )
    );
}

float Single(float3 coord, float3 warp, float amp)
{
    return Single(
        float3(
            coord.x + fnlGetNoise3D(warpState, warp.x, warp.y, warp.z) * amp,
            coord.y + fnlGetNoise3D(warpState, warp.y, warp.x, warp.z) * amp,
            coord.z
        )
    );
}

// Linear

float Single_Linear(float2 coord)
{
    return (Single(coord) + 1) / 2;
}

float Single_Linear(float3 coord)
{
    return (Single(coord) + 1) / 2;
}

float Single_Linear(float2 coord, float2 warp, float amp)
{
    return Single_Linear(
        float2(
            coord.x + fnlGetNoise2D(warpState, warp.x, warp.y) * amp,
            coord.y + fnlGetNoise2D(warpState, warp.y, warp.x) * amp
        )
    );
}

float Single_Linear(float3 coord, float3 warp, float amp)
{
    return Single_Linear(
        float3(
            coord.x + fnlGetNoise3D(warpState, warp.x, warp.y, warp.z) * amp,
            coord.y + fnlGetNoise3D(warpState, warp.y, warp.x, warp.z) * amp,
            coord.z
        )
    );
}

//----

float RotateX(float x, float y)
{
    return x * sin + y * cos;
}
float RotateY(float x, float y)
{
    return x * cos - y * sin;
}

int Index(int x, int y)
{
    if (x >= width || y >= height)
    {
        return -1;
    }
    
    return y * width + x;
}

float NoisePosX(float x)
{
    return ((x - halfWidth) / scale.x);
}
float NoisePosY(float y)
{
    return ((y - halfHeight) / scale.y); 
}

float WarpPosX(float x)
{
    return ((x / warpScale.x) + warpOffset.x) / canvasToScreenRatio.x;
}
float WarpPosY(float y)
{
    return ((y / warpScale.y) + warpOffset.y) / canvasToScreenRatio.y;
}

// Non-Linear

[numthreads(32, 32, 1)]
void Noise2D(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    noise[index] = Single(
        float2(
            NoisePosX(id.x), 
            NoisePosY(id.y)
        )
    );
}

[numthreads(32, 32, 1)]
void Noise2D_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
    
    noise[index] = Single(
        float2(
            RotateX(noiseX, noiseY), 
            RotateY(noiseX, noiseY)
        )
    );
}

[numthreads(32, 32, 1)]
void Noise3D(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    noise[index] = Single(
        float3(
            NoisePosX(id.x), 
            NoisePosY(id.y), 
            offset.z
        )
    );
}

[numthreads(32, 32, 1)]
void Noise3D_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
    
    noise[index] = Single(
        float3(
            RotateX(noiseX, noiseY), 
            RotateY(noiseX, noiseY), 
            offset.z
        )
    );
}

[numthreads(32, 32, 1)]
void WarpNoise2D(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    WarpInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
    
    noise[index] = Single(
        float2(
            noiseX, 
            noiseY
        ), 
        float2(
            WarpPosX(noiseX), 
            WarpPosY(noiseY)
        ), 
        warpAmp
    );
}

[numthreads(32, 32, 1)]
void WarpNoise2D_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    WarpInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
    float warpX = WarpPosX(noiseX);
    float warpY = WarpPosY(noiseY);
    
    noise[index] = Single(
        float2(
            RotateX(noiseX, noiseY), 
            RotateY(noiseX, noiseY)
        ),
        float2(
            RotateX(warpX, warpY), 
            RotateY(warpX, warpY)
        ),
        warpAmp
    );
}

[numthreads(32, 32, 1)]
void WarpNoise3D(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    WarpInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
            
    noise[index] = Single(
        float3(
            noiseX, 
            noiseY, 
            offset.z
        ),
        float3(
            WarpPosX(noiseX), 
            WarpPosY(noiseY), 
            warpOffset.z
        ),
        warpAmp
    );
}

[numthreads(32, 32, 1)]
void WarpNoise3D_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    WarpInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
    float warpX = WarpPosX(noiseX);
    float warpY = WarpPosY(noiseY);
    
    noise[index] = Single(
        float3(
            RotateX(noiseX, noiseY), 
            RotateY(noiseX, noiseY), 
            offset.z
        ),
        float3(
            RotateX(warpX, warpY), 
            RotateY(warpX, warpY), 
            warpOffset.z
        ),
        warpAmp
    );
}

// Linear

[numthreads(32, 32, 1)]
void Noise2D_Linear(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    noise[index] = Single_Linear(
        float2(
            NoisePosX(id.x), 
            NoisePosY(id.y)
        )
    );
}

[numthreads(32, 32, 1)]
void Noise2D_Linear_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
    
    noise[index] = Single_Linear(
        float2(
            RotateX(noiseX, noiseY), 
            RotateY(noiseX, noiseY)
        )
    );
}

[numthreads(32, 32, 1)]
void Noise3D_Linear(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    noise[index] = Single_Linear(
        float3(
            NoisePosX(id.x), 
            NoisePosY(id.y), 
            offset.z
        )
    );
}

[numthreads(32, 32, 1)]
void Noise3D_Linear_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
    
    noise[index] = Single_Linear(
        float3(
            RotateX(noiseX, noiseY), 
            RotateY(noiseX, noiseY), 
            offset.z
        )
    );
}

[numthreads(32, 32, 1)]
void WarpNoise2D_Linear(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    WarpInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
    
    noise[index] = Single_Linear(
        float2(
            noiseX, 
            noiseY
        ),
        float2(
            WarpPosX(noiseX), 
            WarpPosY(noiseY)
        ),
        warpAmp
    );
}

[numthreads(32, 32, 1)]
void WarpNoise2D_Linear_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    WarpInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
    float warpX = WarpPosX(noiseX);
    float warpY = WarpPosY(noiseY);
    
    noise[index] = Single_Linear(
        float2(
            RotateX(noiseX, noiseY), 
            RotateY(noiseX, noiseY)
        ),
        float2(
            RotateX(warpX, warpY), 
            RotateY(warpX, warpY)
        ),
        warpAmp
    );
}

[numthreads(32, 32, 1)]
void WarpNoise3D_Linear(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    WarpInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
            
    noise[index] = Single_Linear(
        float3(
            noiseX, 
            noiseY, 
            offset.z
        ),
        float3(
            WarpPosX(noiseX), 
            WarpPosY(noiseY), 
            warpOffset.z
        ),
        warpAmp
    );
}

[numthreads(32, 32, 1)]
void WarpNoise3D_Linear_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    if (index == -1)
        return;
    
    NoiseInit();
    WarpInit();
    
    float noiseX = NoisePosX(id.x);
    float noiseY = NoisePosY(id.y);
    float warpX = WarpPosX(noiseX);
    float warpY = WarpPosY(noiseY);
            
    noise[index] = Single_Linear(
        float3(
            RotateX(noiseX, noiseY), 
            RotateY(noiseX, noiseY), 
            offset.z
        ),
        float3(
            RotateX(warpX, warpY), 
            RotateY(warpX, warpY), 
            warpOffset.z
        ),
        warpAmp
    );
}