#pragma kernel Normal
#pragma kernel Normal_Roll
#pragma kernel Normal_Invert
#pragma kernel Normal_Invert_Roll
#pragma kernel Noise
#pragma kernel Noise_Roll
#pragma kernel Noise_Invert
#pragma kernel Noise_Invert_Roll

float sin, cos;

int width;
int height;

float power;

float2 scale;
float2 range;

float warp;
float ratio;

StructuredBuffer<float> pointsX;
StructuredBuffer<float> pointsY;

RWStructuredBuffer<float> values;

float RotateX(float x, float y)
{
    return x * sin + y * cos;
}
float RotateY(float x, float y)
{
    return x * cos - y * sin;
}

float InverseLerp(float a, float b, float t)
{
    return (t - a) / (b - a);
}

float GetValue(float x, float y, float2 scale)
{
    return sqrt(
        abs(pow(x * scale.x, 2)) +
        abs(pow(y * scale.y, 2))
    );
}
float GetValue_Noise(float value, float x, float y, float2 scale)
{
    value = GetValue(x, y, scale) + (value * warp);
    value = clamp(value, 0, warp + 1.0f);
    value = InverseLerp(0, warp + 1, value);
    
    return value;
}

int Index(int x, int y)
{
    if (x >= width)
        return -1;
    
    if (y >= height)
        return -1;
    
    return y * width + x;
}

// Normal

[numthreads(32, 32, 1)]
void Normal(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    
    values[index] = GetValue(pointsX[id.x], pointsY[id.y], scale);
    
    values[index] = InverseLerp(0, range.y, values[index]);
    values[index] = pow(values[index], max(abs(power), 1));
    
    values[index] = clamp(values[index], range.x, 1);
}

[numthreads(32, 32, 1)]
void Normal_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    
    values[index] = GetValue(
        RotateX(pointsX[id.x], pointsY[id.y]),
        RotateY(pointsX[id.x], pointsY[id.y]),
        scale
    );
    
    values[index] = InverseLerp(0, range.y, values[index]);
    values[index] = pow(values[index], max(abs(power), 1));
    
    values[index] = clamp(values[index], range.x, 1);
}

// Normal Invert

[numthreads(32, 32, 1)]
void Normal_Invert(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    
    values[index] = GetValue(pointsX[id.x], pointsY[id.y], scale);
    
    values[index] = InverseLerp(0, range.y, values[index]);
    values[index] = pow(values[index], max(abs(power), 1));
    
    values[index] = 1 - values[index];
    
    values[index] = clamp(values[index], range.x, 1);
}

[numthreads(32, 32, 1)]
void Normal_Invert_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    
    values[index] = GetValue(
        RotateX(pointsX[id.x], pointsY[id.y]),
        RotateY(pointsX[id.x], pointsY[id.y]),
        scale
    );
    
    values[index] = InverseLerp(0, range.y, values[index]);
    values[index] = pow(values[index], max(abs(power), 1));
    
    values[index] = 1 - values[index];
    
    values[index] = clamp(values[index], range.x, 1);
}

// Noise

[numthreads(32, 32, 1)]
void Noise(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    
    values[index] = GetValue_Noise(values[index], pointsX[id.x], pointsY[id.y], scale);
    
    values[index] = InverseLerp(0, range.y, values[index]);
    values[index] = pow(values[index], max(abs(power), 1));
    
    values[index] = clamp(values[index], range.x, 1);
}

[numthreads(32, 32, 1)]
void Noise_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    
    values[index] = GetValue_Noise(
        values[index],
        RotateX(pointsX[id.x], pointsY[id.y]),
        RotateY(pointsX[id.x], pointsY[id.y]),
        scale
    );
    
    values[index] = InverseLerp(0, range.y, values[index]);
    values[index] = pow(values[index], max(abs(power), 1));
    
    values[index] = clamp(values[index], range.x, 1);
}

// Noise Invert

[numthreads(32, 32, 1)]
void Noise_Invert(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    
    values[index] = GetValue_Noise(values[index], pointsX[id.x], pointsY[id.y], scale);
    
    values[index] = InverseLerp(0, range.y, values[index]);
    values[index] = pow(values[index], max(abs(power), 1));
    
    values[index] = 1 - values[index];
    
    values[index] = clamp(values[index], range.x, 1);
}

[numthreads(32,32,1)]
void Noise_Invert_Roll(uint3 id : SV_DispatchThreadID)
{
    int index = Index(id.x, id.y);
    
    values[index] = GetValue_Noise(
        values[index],
        RotateX(pointsX[id.x], pointsY[id.y]),
        RotateY(pointsX[id.x], pointsY[id.y]),
        scale
    );
    
    values[index] = InverseLerp(0, range.y, values[index]);
    values[index] = pow(values[index], max(abs(power), 1));
    
    values[index] = 1 - values[index];
    
    values[index] = clamp(values[index], range.x, 1);
}
